const getData  = async (id:string)=>{
    const resp = await fetch(  "https://dios.dianliantech.com/api-v2/portal/news/queryDetail",
    {
      method: "POST",
      //   next: { revalidate: 10 },
      body: JSON.stringify({
       id
      }),
      headers: {
        "Content-Type": "application/json",
        Entcode: "dlkj6868",
      },
    })

    return resp.json()
}


export const metadata = {
    title: 'postDetail',
    description: 'Generated by create next app',
  }

async function   PostId({params}:{params:{postId:string}}) {

    const data = await getData(params.postId)
    console.log(data)
    return ( <div><div >{data.datas.title}</div>
    <div dangerouslySetInnerHTML={{ __html: data.datas.content }}></div></div> );
}

export default PostId;