export const metadata = {
    title: 'org',
    description: 'Generated by create next app',
  }
  
  export default function OrgLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <section>
          orgLayout
          {children}
      </section>
    )
  }
  