



export const metadata = {
  title: 'user',
  description: 'Generated by create next app',
}

export default function UserLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <section>
        userLayout
        {children}
    </section>
  )
}
